name: Unit Testing for Plugins

on:
  push:
    branches:
      - trunk
      - 'release/**'
    # Only run if PHP-related files changed.
    paths:
      - '.github/workflows/php-test-plugins.yml'
      - 'plugins/**.php'
      - '.wp-env.json'
      - '**/package.json'
      - 'package-lock.json'
      - 'phpunit.xml.dist'
      - 'tests/multisite.xml'
      - 'composer.json'
      - 'composer.lock'
  pull_request:
    # Only run if PHP-related files changed.
    paths:
      - '.github/workflows/php-test-plugins.yml'
      - 'plugins/**.php'
      - '.wp-env.json'
      - '**/package.json'
      - 'package-lock.json'
      - 'phpunit.xml.dist'
      - 'tests/multisite.xml'
      - 'composer.json'
      - 'composer.lock'
    types:
      - opened
      - reopened
      - synchronize

jobs:
  php-test-plugins:
    name: "PHP ${{ matrix.php }} / WP ${{ matrix.wp }}"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.0', '7.4', '7.3', '7.2']
        wp: [ 'latest' ]
        coverage: [false]
        include:
          - php: '7.4'
            wp: '6.5'
          - php: '8.3'
            wp: 'trunk'
            phpunit: '9.6'
          - php: '8.2'
            phpunit: '9.6'
            wp: 'latest'
            coverage: true
    env:
      WP_ENV_PHP_VERSION: ${{ matrix.php }}
      WP_ENV_CORE: ${{ matrix.wp == 'trunk' && 'WordPress/WordPress' || format( 'https://wordpress.org/wordpress-{0}.zip', matrix.wp ) }}
    steps:
      - uses: styfle/cancel-workflow-action@0.12.1
      - uses: actions/checkout@v4
      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: npm install
        run: npm ci
      - name: Build assets
        run: npm run build
      - name: Install WordPress
        run: npm run wp-env start
      - name: Composer Install
        run: npm run wp-env run tests-cli -- --env-cwd="wp-content/plugins/$(basename $(pwd))" composer install --no-interaction --no-progress
      - name: Update Composer Dependencies
        run: composer update --with-all-dependencies --no-interaction --no-progress
      - name: Install PHPUnit
        run: composer require --dev phpunit/phpunit:${{ matrix.phpunit }}
        if: matrix.phpunit != ''
      - name: Running single site unit tests
        run: |
          if [ "${{ matrix.coverage }}" == "true" ]; then
            npm run test-php:performance-lab -- -- -- --coverage-clover=coverage-performance-lab-${{ github.sha }}.xml
            npm run test-php:auto-sizes -- -- -- --coverage-clover=coverage-auto-sizes-${{ github.sha }}.xml
            npm run test-php:dominant-color-images -- -- -- --coverage-clover=coverage-dominant-color-images-${{ github.sha }}.xml
            npm run test-php:embed-optimizer -- -- -- --coverage-clover=coverage-embed-optimizer-${{ github.sha }}.xml
            npm run test-php:image-prioritizer -- -- -- --coverage-clover=coverage-image-prioritizer-${{ github.sha }}.xml
            npm run test-php:optimization-detective -- -- -- --coverage-clover=coverage-optimization-detective-${{ github.sha }}.xml
            npm run test-php:speculation-rules -- -- -- --coverage-clover=coverage-speculation-rules-${{ github.sha }}.xml
            npm run test-php:web-worker-offloading -- -- -- --coverage-clover=coverage-web-worker-offloading-${{ github.sha }}.xml
            npm run test-php:webp-uploads -- -- -- --coverage-clover=coverage-webp-uploads-${{ github.sha }}.xml
          else
            npm run test-php
          fi
      - name: Running multisite unit tests
        run: |
          if [ "${{ matrix.coverage }}" == "true" ]; then
            npm run test-php-multisite:performance-lab -- -- -- --coverage-clover=coverage-multisite-performance-lab-${{ github.sha }}.xml
            npm run test-php-multisite:auto-sizes -- -- -- --coverage-clover=coverage-multisite-auto-sizes-${{ github.sha }}.xml
            npm run test-php-multisite:dominant-color-images -- -- -- --coverage-clover=coverage-multisite-dominant-color-images-${{ github.sha }}.xml
            npm run test-php-multisite:embed-optimizer -- -- -- --coverage-clover=coverage-multisite-embed-optimizer-${{ github.sha }}.xml
            npm run test-php-multisite:image-prioritizer -- -- -- --coverage-clover=coverage-multisite-image-prioritizer-${{ github.sha }}.xml
            npm run test-php-multisite:optimization-detective -- -- -- --coverage-clover=coverage-multisite-optimization-detective-${{ github.sha }}.xml
            npm run test-php-multisite:speculation-rules -- -- -- --coverage-clover=coverage-multisite-speculation-rules-${{ github.sha }}.xml
            npm run test-php-multisite:web-worker-offloading -- -- -- --coverage-clover=coverage-multisite-web-worker-offloading-${{ github.sha }}.xml
            npm run test-php-multisite:webp-uploads -- -- -- --coverage-clover=coverage-multisite-webp-uploads-${{ github.sha }}.xml
          else
            npm run test-php-multisite
          fi
      - name: Upload single site coverage reports to Codecov
        if: ${{ matrix.coverage == true }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: |
            coverage-performance-lab-${{ github.sha }}.xml
            coverage-auto-sizes-${{ github.sha }}.xml
            coverage-dominant-color-images-${{ github.sha }}.xml
            coverage-embed-optimizer-${{ github.sha }}.xml
            coverage-image-prioritizer-${{ github.sha }}.xml
            coverage-optimization-detective-${{ github.sha }}.xml
            coverage-speculation-rules-${{ github.sha }}.xml
            coverage-web-worker-offloading-${{ github.sha }}.xml
            coverage-webp-uploads-${{ github.sha }}.xml
          flags: single
          name: ${{ matrix.php }}-single-site-coverage
          fail_ci_if_error: true
      - name: Upload multisite coverage reports to Codecov
        if: ${{ matrix.coverage == true }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: |
            coverage-multisite-performance-lab-${{ github.sha }}.xml
            coverage-multisite-auto-sizes-${{ github.sha }}.xml
            coverage-multisite-dominant-color-images-${{ github.sha }}.xml
            coverage-multisite-embed-optimizer-${{ github.sha }}.xml
            coverage-multisite-image-prioritizer-${{ github.sha }}.xml
            coverage-multisite-optimization-detective-${{ github.sha }}.xml
            coverage-multisite-speculation-rules-${{ github.sha }}.xml
            coverage-multisite-web-worker-offloading-${{ github.sha }}.xml
            coverage-multisite-webp-uploads-${{ github.sha }}.xml
          flags: multisite
          name: ${{ matrix.php }}-multisite-coverage
          fail_ci_if_error: true
