name: Unit Testing for Plugins

on:
  push:
    branches:
      - trunk
      - 'release/**'
    # Only run if PHP-related files changed.
    paths:
      - '.github/workflows/php-test-plugins.yml'
      - 'plugins/**.php'
      - '.wp-env.json'
      - '**/package.json'
      - 'package-lock.json'
      - 'phpunit.xml.dist'
      - 'tests/multisite.xml'
      - 'composer.json'
      - 'composer.lock'
  pull_request:
    # Only run if PHP-related files changed.
    paths:
      - '.github/workflows/php-test-plugins.yml'
      - 'plugins/**.php'
      - '.wp-env.json'
      - '**/package.json'
      - 'package-lock.json'
      - 'phpunit.xml.dist'
      - 'tests/multisite.xml'
      - 'composer.json'
      - 'composer.lock'
    types:
      - opened
      - reopened
      - synchronize

jobs:
  php-test-plugins:
    name: "PHP ${{ matrix.php }} / WP ${{ matrix.wp }}"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.0', '7.4', '7.3', '7.2']
        wp: [ 'latest' ]
        coverage: [false]
        include:
          - php: '7.4'
            wp: '6.6'
          - php: '8.3'
            wp: 'trunk'
          - php: '8.2'
            phpunit: '9.6'
            wp: 'latest'
            coverage: ${{ !startsWith(github.actor, 'dependabot') }}
    env:
      WP_ENV_PHP_VERSION: ${{ matrix.php }}
      WP_ENV_CORE: ${{ matrix.wp == 'trunk' && 'WordPress/WordPress' || format( 'https://wordpress.org/wordpress-{0}.zip', matrix.wp ) }}
    steps:
      - uses: styfle/cancel-workflow-action@0.12.1
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for accurate merge-base resolution.
      - name: Determine affected plugins
        id: affected-plugins
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: |
          # For push to 'trunk' or 'release/**' events, test all plugins regardless of changes.
          if [ "$GITHUB_EVENT_NAME" = "push" ]; then
            AFFECTED_PLUGINS=($(ls plugins))
            echo "Event: $GITHUB_EVENT_NAME - Running tests for all plugins. Affected plugins: ${AFFECTED_PLUGINS[*]}"
            echo "plugins=${AFFECTED_PLUGINS[*]}" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Get PR-specific changes using merge-base diff.
          CHANGED_FILES=$(git diff --name-only HEAD^1...HEAD^2)
          echo "Changed files:"
          echo "$CHANGED_FILES"

          # Check for global changes (any file outside plugins/).
          GLOBAL_CHANGES=$(echo "$CHANGED_FILES" | grep -v '^plugins/')
          if [ -n "$GLOBAL_CHANGES" ]; then
            AFFECTED_PLUGINS=($(ls plugins))
            echo "Global changes detected; testing all plugins: ${AFFECTED_PLUGINS[*]}"
          else
            # Extract affected plugins and their dependencies.
            AFFECTED_PLUGINS=($(echo "$CHANGED_FILES" | grep '^plugins/' | cut -d'/' -f2 | sort -u))

            # Define plugin dependencies (e.g., optimization-detective triggers others).
            declare -A PLUGIN_DEPENDENCIES=(
              ["optimization-detective"]="embed-optimizer image-prioritizer"
            )

            # Add dependent plugins to the list.
            for PLUGIN in "${AFFECTED_PLUGINS[@]}"; do
              if [ -n "${PLUGIN_DEPENDENCIES[$PLUGIN]}" ]; then
                for DEP in ${PLUGIN_DEPENDENCIES[$PLUGIN]}; do
                  if [[ ! " ${AFFECTED_PLUGINS[@]} " =~ " ${DEP} " ]]; then
                    AFFECTED_PLUGINS+=("$DEP")
                  fi
                done
              fi
            done

            # Remove duplicate entries.
            AFFECTED_PLUGINS=($(echo "${AFFECTED_PLUGINS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))
            echo "Plugins with changes: ${AFFECTED_PLUGINS[*]}"
          fi

          # Output the list of plugins to test.
          echo "plugins=${AFFECTED_PLUGINS[*]}" >> $GITHUB_OUTPUT
      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: npm install
        run: npm ci
      - name: Build assets
        run: npm run build
      - name: Install WordPress
        run: |
          if [ "${{ matrix.coverage }}" == "true" ]; then
            npm run wp-env start -- --xdebug=coverage
          else
            npm run wp-env start
          fi
      - name: Composer Install
        run: npm run wp-env run tests-cli -- --env-cwd="wp-content/plugins/$(basename $(pwd))" composer install --no-interaction --no-progress
      - name: Update Composer Dependencies
        run: composer update --with-all-dependencies --no-interaction --no-progress
      - name: Install PHPUnit
        run: |
          if [ "${{ matrix.php }}" == "8.2" ]; then
            composer require phpunit/phpunit:${{ matrix.phpunit }} --with-all-dependencies --ignore-platform-reqs
          else
            composer require --dev phpunit/phpunit:${{ matrix.phpunit }}
          fi
        if: matrix.phpunit != ''
      - name: Running single site unit tests
        run: |
          if [ "${{ matrix.coverage }}" == "true" ]; then
            for PLUGIN in ${{ steps.affected-plugins.outputs.plugins }}; do
              npm run test-php:$PLUGIN -- -- -- --coverage-clover=./single-site-reports/coverage-$PLUGIN.xml
            done
          else
            for PLUGIN in ${{ steps.affected-plugins.outputs.plugins }}; do
              npm run test-php:$PLUGIN
            done
          fi
      - name: Running multisite unit tests
        run: |
          if [ "${{ matrix.coverage }}" == "true" ]; then
            for PLUGIN in ${{ steps.affected-plugins.outputs.plugins }}; do
              npm run test-php-multisite:$PLUGIN -- -- -- --coverage-clover=./multisite-reports/coverage-multisite-$PLUGIN.xml
            done
          else
            for PLUGIN in ${{ steps.affected-plugins.outputs.plugins }}; do
              npm run test-php-multisite:$PLUGIN
            done
          fi
      - name: Upload single site coverage reports to Codecov
        if: ${{ matrix.coverage == true }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./single-site-reports
          flags: single
          name: ${{ matrix.php }}-single-site-coverage
          fail_ci_if_error: true
      - name: Upload multisite coverage reports to Codecov
        if: ${{ matrix.coverage == true }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./multisite-reports
          flags: multisite
          name: ${{ matrix.php }}-multisite-coverage
          fail_ci_if_error: true
